import type { Metadata } from "next";
import "./globals.css";
import { Recursive } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import SessionWrapper from "@/components/SessionWrapper";
import { Toaster } from "sonner";
import Loading from "./loading";
import { Suspense } from "react";
import { CartProvider } from "@/lib/cart_context";

const recursive = Recursive({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  // title: "Mobile Store",
  title: "Market Store",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: Readonly<RootLayoutProps>) {


  return (
    <SessionWrapper>
      <html lang="en" className={recursive.className} suppressHydrationWarning>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* ✅ Wrap everything in CartProvider */}
            <CartProvider>
              <main className="flex flex-col min-h-[calc(100vh-3.5rem-1px)]">
                <Toaster richColors position="bottom-right" />
                <Suspense fallback={<Loading />}>
                  <Toaster richColors position="bottom-right" />
                  {children}
                </Suspense>
              </main>
            </CartProvider>
          </ThemeProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
